### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Rezaamnn** [kart33k/UltimateH1BSponsorChecker#26] opened 2023-09-22 00:41 UTC
Hello, since today the extension isn't working. I also got linkedin premium I don't know if that caused the checker to not work or not.

**Comment by kart33k** [comment] 2023-09-22 01:40
There was a linkedin update which broke the extension. The issue is fixed and will be released in few days, thanks. Added support for Google jobs as well.

**Closed as completed** 2023-09-29 00:21 UTC
